name: nix flow
on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - release/**
    tags:
      - "*"

env:
  NIXPKGS_ALLOW_INSECURE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-solomachine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: crypto-com
      - name: Run integration tests
        run: make nix-integration-test-solomachine
      - name: Convert coverage data
        run: |
           nix profile install nixpkgs#go_1_22
           go tool covdata textfmt -i=coverage -o profile.txt
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./profile.txt
          flags: integration_tests_solomachine
      - name: Tar debug files
        if: failure()
        run: tar cfz debug_files_solomachine.tar.gz -C ${TMPDIR-/tmp}/pytest-of-runner .
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: debug_files_solomachine
          path: debug_files_solomachine.tar.gz
          if-no-files-found: ignore
